<Project InitialTargets="ValidateGamePath">
	<Import Project="$(MSBuildThisFileDirectory)\GameFolder.props" Condition="Exists('$(MSBuildThisFileDirectory)\GameFolder.props')" />
	<!-- Add a GameFolder.props file to this solution to set your game path -->
	<!-- 
		<Project>
		  <PropertyGroup>
			<GameFolder>C:\Program Files (x86)\Steam\steamapps\common\GTFO</GameFolder>
		   </PropertyGroup>
		</Project>
    -->
	<Target Name="ValidateGamePath">
		<Error Text="The GameFolder property must be set to the Game folder." Condition="'$(GameFolder)' == '' or !Exists('$(GameFolder)')" />
	</Target>

	<!-- Path Properties -->
	<PropertyGroup>
		<BIELibsFolder>$(BepInEx)\core</BIELibsFolder>
		<PluginsFolder>$(BepInEx)\plugins</PluginsFolder>
		<InteropLibsFolder>$(BepInEx)\interop</InteropLibsFolder>
	</PropertyGroup>

	<!-- Assemblies -->
	<ItemGroup>
		<!-- BepInEx -->
		<Reference Include="$(BIELibsFolder)\BepInEx.*.dll" Private="false" />
		<Reference Include="$(BIELibsFolder)\0Harmony.dll" Private="false" />
		<Reference Include="$(BIELibsFolder)\Il2CppInterop.Runtime.dll" Private="false" />
		<Reference Include="$(BIELibsFolder)\MonoMod.RuntimeDetour.dll" Private="false" />
		<Reference Include="$(BIELibsFolder)\SemanticVersioning.dll" Private="false" />

		<!-- Game Assemblies -->
		<Reference Include="$(InteropLibsFolder)/*.dll" Private="false" />
		<Reference Remove="$(InteropLibsFolder)/netstandard.dll" />
		<Reference Remove="$(InteropLibsFolder)/mscorlib.dll" />
		<Reference Remove="$(InteropLibsFolder)/Newtonsoft.Json.dll" />
	</ItemGroup>

	<!-- Plugins -->
	<ItemGroup>
		<Reference Include="$(PluginsFolder)/GTFO-API.dll" Private="false" />
		<Reference Include="$(PluginsFolder)\**\InjectLib.dll" Private="false" />
		<Reference Include="$(PluginsFolder)\**\MTFO.Ext.PartialData.dll" Private="false" />
	</ItemGroup>
</Project>