<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<!-- Use the following property to set your preferred Thunderstore profile to compile in -->
		<Profile>Plugin Testing</Profile>

		<!-- Thunderstore author's name as in $(BuildDirectory) -->
		<Author>hirnukuono</Author>

		<!-- Name of the dll -->
		<AssemblyName>ExtraEnemyCustomization</AssemblyName>

		<!-- Mod manager name -->
		<ModManager>com.kesomannen.gale</ModManager>

		<BepInEx>$(AppData)\$(ModManager)\GTFO\profiles\$(Profile)\BepInEx</BepInEx>
		<BuildDirectory>$(BepInEx)\plugins\$(Author)-$(SolutionName)\</BuildDirectory>
		<RootNamespace>EEC</RootNamespace>
		<OutputPath>$(BuildDirectory)</OutputPath>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
		<Platforms>AnyCPU;x64</Platforms>
		<TargetFramework>net6</TargetFramework>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<DebugType>None</DebugType>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>
	<Target Name="PostBuild" BeforeTargets="PostBuildEvent">
		<Delete Files="$(OutputPath)$(AssemblyName).deps.json" />
	</Target>

	<Import Project="Dependencies.props" />

</Project>